// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DSMsg.proto

#ifndef PROTOBUF_DSMsg_2eproto__INCLUDED
#define PROTOBUF_DSMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_DSMsg_2eproto();
void protobuf_AssignDesc_DSMsg_2eproto();
void protobuf_ShutdownFile_DSMsg_2eproto();

class SysInterfaceStruct;
class InterfaceSelectReq;
class InterfaceSelectAck;
class InterfaceInsertReq;
class InterfaceInsertAck;
class InterfaceUpdateReq;
class InterfaceUpdateAck;
class InterfaceDeleteReq;
class InterfaceDeleteAck;

// ===================================================================

class SysInterfaceStruct : public ::google::protobuf::Message {
 public:
  SysInterfaceStruct();
  virtual ~SysInterfaceStruct();

  SysInterfaceStruct(const SysInterfaceStruct& from);

  inline SysInterfaceStruct& operator=(const SysInterfaceStruct& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SysInterfaceStruct& default_instance();

  void Swap(SysInterfaceStruct* other);

  // implements Message ----------------------------------------------

  SysInterfaceStruct* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SysInterfaceStruct& from);
  void MergeFrom(const SysInterfaceStruct& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 InterfaceID = 1;
  inline bool has_interfaceid() const;
  inline void clear_interfaceid();
  static const int kInterfaceIDFieldNumber = 1;
  inline ::google::protobuf::int32 interfaceid() const;
  inline void set_interfaceid(::google::protobuf::int32 value);

  // optional int32 DSSVRID = 2;
  inline bool has_dssvrid() const;
  inline void clear_dssvrid();
  static const int kDSSVRIDFieldNumber = 2;
  inline ::google::protobuf::int32 dssvrid() const;
  inline void set_dssvrid(::google::protobuf::int32 value);

  // optional string IFName = 3;
  inline bool has_ifname() const;
  inline void clear_ifname();
  static const int kIFNameFieldNumber = 3;
  inline const ::std::string& ifname() const;
  inline void set_ifname(const ::std::string& value);
  inline void set_ifname(const char* value);
  inline void set_ifname(const char* value, size_t size);
  inline ::std::string* mutable_ifname();
  inline ::std::string* release_ifname();
  inline void set_allocated_ifname(::std::string* ifname);

  // optional string IFPath = 4;
  inline bool has_ifpath() const;
  inline void clear_ifpath();
  static const int kIFPathFieldNumber = 4;
  inline const ::std::string& ifpath() const;
  inline void set_ifpath(const ::std::string& value);
  inline void set_ifpath(const char* value);
  inline void set_ifpath(const char* value, size_t size);
  inline ::std::string* mutable_ifpath();
  inline ::std::string* release_ifpath();
  inline void set_allocated_ifpath(::std::string* ifpath);

  // optional int32 IsEnable = 5;
  inline bool has_isenable() const;
  inline void clear_isenable();
  static const int kIsEnableFieldNumber = 5;
  inline ::google::protobuf::int32 isenable() const;
  inline void set_isenable(::google::protobuf::int32 value);

  // optional string DescComment = 6;
  inline bool has_desccomment() const;
  inline void clear_desccomment();
  static const int kDescCommentFieldNumber = 6;
  inline const ::std::string& desccomment() const;
  inline void set_desccomment(const ::std::string& value);
  inline void set_desccomment(const char* value);
  inline void set_desccomment(const char* value, size_t size);
  inline ::std::string* mutable_desccomment();
  inline ::std::string* release_desccomment();
  inline void set_allocated_desccomment(::std::string* desccomment);

  // @@protoc_insertion_point(class_scope:SysInterfaceStruct)
 private:
  inline void set_has_interfaceid();
  inline void clear_has_interfaceid();
  inline void set_has_dssvrid();
  inline void clear_has_dssvrid();
  inline void set_has_ifname();
  inline void clear_has_ifname();
  inline void set_has_ifpath();
  inline void clear_has_ifpath();
  inline void set_has_isenable();
  inline void clear_has_isenable();
  inline void set_has_desccomment();
  inline void clear_has_desccomment();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 interfaceid_;
  ::google::protobuf::int32 dssvrid_;
  ::std::string* ifname_;
  ::std::string* ifpath_;
  ::std::string* desccomment_;
  ::google::protobuf::int32 isenable_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static SysInterfaceStruct* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceSelectReq : public ::google::protobuf::Message {
 public:
  InterfaceSelectReq();
  virtual ~InterfaceSelectReq();

  InterfaceSelectReq(const InterfaceSelectReq& from);

  inline InterfaceSelectReq& operator=(const InterfaceSelectReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceSelectReq& default_instance();

  void Swap(InterfaceSelectReq* other);

  // implements Message ----------------------------------------------

  InterfaceSelectReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceSelectReq& from);
  void MergeFrom(const InterfaceSelectReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 DSSVRID = 2;
  inline bool has_dssvrid() const;
  inline void clear_dssvrid();
  static const int kDSSVRIDFieldNumber = 2;
  inline ::google::protobuf::int32 dssvrid() const;
  inline void set_dssvrid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:InterfaceSelectReq)
 private:
  inline void set_has_dssvrid();
  inline void clear_has_dssvrid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 dssvrid_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceSelectReq* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceSelectAck : public ::google::protobuf::Message {
 public:
  InterfaceSelectAck();
  virtual ~InterfaceSelectAck();

  InterfaceSelectAck(const InterfaceSelectAck& from);

  inline InterfaceSelectAck& operator=(const InterfaceSelectAck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceSelectAck& default_instance();

  void Swap(InterfaceSelectAck* other);

  // implements Message ----------------------------------------------

  InterfaceSelectAck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceSelectAck& from);
  void MergeFrom(const InterfaceSelectAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SysInterfaceStruct CfgItems = 2;
  inline int cfgitems_size() const;
  inline void clear_cfgitems();
  static const int kCfgItemsFieldNumber = 2;
  inline const ::SysInterfaceStruct& cfgitems(int index) const;
  inline ::SysInterfaceStruct* mutable_cfgitems(int index);
  inline ::SysInterfaceStruct* add_cfgitems();
  inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
      cfgitems() const;
  inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
      mutable_cfgitems();

  // @@protoc_insertion_point(class_scope:InterfaceSelectAck)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct > cfgitems_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceSelectAck* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceInsertReq : public ::google::protobuf::Message {
 public:
  InterfaceInsertReq();
  virtual ~InterfaceInsertReq();

  InterfaceInsertReq(const InterfaceInsertReq& from);

  inline InterfaceInsertReq& operator=(const InterfaceInsertReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceInsertReq& default_instance();

  void Swap(InterfaceInsertReq* other);

  // implements Message ----------------------------------------------

  InterfaceInsertReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceInsertReq& from);
  void MergeFrom(const InterfaceInsertReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SysInterfaceStruct CfgItems = 2;
  inline int cfgitems_size() const;
  inline void clear_cfgitems();
  static const int kCfgItemsFieldNumber = 2;
  inline const ::SysInterfaceStruct& cfgitems(int index) const;
  inline ::SysInterfaceStruct* mutable_cfgitems(int index);
  inline ::SysInterfaceStruct* add_cfgitems();
  inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
      cfgitems() const;
  inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
      mutable_cfgitems();

  // @@protoc_insertion_point(class_scope:InterfaceInsertReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct > cfgitems_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceInsertReq* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceInsertAck : public ::google::protobuf::Message {
 public:
  InterfaceInsertAck();
  virtual ~InterfaceInsertAck();

  InterfaceInsertAck(const InterfaceInsertAck& from);

  inline InterfaceInsertAck& operator=(const InterfaceInsertAck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceInsertAck& default_instance();

  void Swap(InterfaceInsertAck* other);

  // implements Message ----------------------------------------------

  InterfaceInsertAck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceInsertAck& from);
  void MergeFrom(const InterfaceInsertAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Ret = 2;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 2;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:InterfaceInsertAck)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ret_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceInsertAck* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceUpdateReq : public ::google::protobuf::Message {
 public:
  InterfaceUpdateReq();
  virtual ~InterfaceUpdateReq();

  InterfaceUpdateReq(const InterfaceUpdateReq& from);

  inline InterfaceUpdateReq& operator=(const InterfaceUpdateReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceUpdateReq& default_instance();

  void Swap(InterfaceUpdateReq* other);

  // implements Message ----------------------------------------------

  InterfaceUpdateReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceUpdateReq& from);
  void MergeFrom(const InterfaceUpdateReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SysInterfaceStruct CfgItems = 2;
  inline int cfgitems_size() const;
  inline void clear_cfgitems();
  static const int kCfgItemsFieldNumber = 2;
  inline const ::SysInterfaceStruct& cfgitems(int index) const;
  inline ::SysInterfaceStruct* mutable_cfgitems(int index);
  inline ::SysInterfaceStruct* add_cfgitems();
  inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
      cfgitems() const;
  inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
      mutable_cfgitems();

  // @@protoc_insertion_point(class_scope:InterfaceUpdateReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct > cfgitems_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceUpdateReq* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceUpdateAck : public ::google::protobuf::Message {
 public:
  InterfaceUpdateAck();
  virtual ~InterfaceUpdateAck();

  InterfaceUpdateAck(const InterfaceUpdateAck& from);

  inline InterfaceUpdateAck& operator=(const InterfaceUpdateAck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceUpdateAck& default_instance();

  void Swap(InterfaceUpdateAck* other);

  // implements Message ----------------------------------------------

  InterfaceUpdateAck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceUpdateAck& from);
  void MergeFrom(const InterfaceUpdateAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Ret = 2;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 2;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:InterfaceUpdateAck)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ret_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceUpdateAck* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceDeleteReq : public ::google::protobuf::Message {
 public:
  InterfaceDeleteReq();
  virtual ~InterfaceDeleteReq();

  InterfaceDeleteReq(const InterfaceDeleteReq& from);

  inline InterfaceDeleteReq& operator=(const InterfaceDeleteReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceDeleteReq& default_instance();

  void Swap(InterfaceDeleteReq* other);

  // implements Message ----------------------------------------------

  InterfaceDeleteReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceDeleteReq& from);
  void MergeFrom(const InterfaceDeleteReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SysInterfaceStruct CfgItems = 2;
  inline int cfgitems_size() const;
  inline void clear_cfgitems();
  static const int kCfgItemsFieldNumber = 2;
  inline const ::SysInterfaceStruct& cfgitems(int index) const;
  inline ::SysInterfaceStruct* mutable_cfgitems(int index);
  inline ::SysInterfaceStruct* add_cfgitems();
  inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
      cfgitems() const;
  inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
      mutable_cfgitems();

  // @@protoc_insertion_point(class_scope:InterfaceDeleteReq)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct > cfgitems_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceDeleteReq* default_instance_;
};
// -------------------------------------------------------------------

class InterfaceDeleteAck : public ::google::protobuf::Message {
 public:
  InterfaceDeleteAck();
  virtual ~InterfaceDeleteAck();

  InterfaceDeleteAck(const InterfaceDeleteAck& from);

  inline InterfaceDeleteAck& operator=(const InterfaceDeleteAck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InterfaceDeleteAck& default_instance();

  void Swap(InterfaceDeleteAck* other);

  // implements Message ----------------------------------------------

  InterfaceDeleteAck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const InterfaceDeleteAck& from);
  void MergeFrom(const InterfaceDeleteAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 Ret = 2;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 2;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:InterfaceDeleteAck)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ret_;
  friend void  protobuf_AddDesc_DSMsg_2eproto();
  friend void protobuf_AssignDesc_DSMsg_2eproto();
  friend void protobuf_ShutdownFile_DSMsg_2eproto();

  void InitAsDefaultInstance();
  static InterfaceDeleteAck* default_instance_;
};
// ===================================================================


// ===================================================================

// SysInterfaceStruct

// optional int32 InterfaceID = 1;
inline bool SysInterfaceStruct::has_interfaceid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SysInterfaceStruct::set_has_interfaceid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SysInterfaceStruct::clear_has_interfaceid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SysInterfaceStruct::clear_interfaceid() {
  interfaceid_ = 0;
  clear_has_interfaceid();
}
inline ::google::protobuf::int32 SysInterfaceStruct::interfaceid() const {
  // @@protoc_insertion_point(field_get:SysInterfaceStruct.InterfaceID)
  return interfaceid_;
}
inline void SysInterfaceStruct::set_interfaceid(::google::protobuf::int32 value) {
  set_has_interfaceid();
  interfaceid_ = value;
  // @@protoc_insertion_point(field_set:SysInterfaceStruct.InterfaceID)
}

// optional int32 DSSVRID = 2;
inline bool SysInterfaceStruct::has_dssvrid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SysInterfaceStruct::set_has_dssvrid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SysInterfaceStruct::clear_has_dssvrid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SysInterfaceStruct::clear_dssvrid() {
  dssvrid_ = 0;
  clear_has_dssvrid();
}
inline ::google::protobuf::int32 SysInterfaceStruct::dssvrid() const {
  // @@protoc_insertion_point(field_get:SysInterfaceStruct.DSSVRID)
  return dssvrid_;
}
inline void SysInterfaceStruct::set_dssvrid(::google::protobuf::int32 value) {
  set_has_dssvrid();
  dssvrid_ = value;
  // @@protoc_insertion_point(field_set:SysInterfaceStruct.DSSVRID)
}

// optional string IFName = 3;
inline bool SysInterfaceStruct::has_ifname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SysInterfaceStruct::set_has_ifname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SysInterfaceStruct::clear_has_ifname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SysInterfaceStruct::clear_ifname() {
  if (ifname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifname_->clear();
  }
  clear_has_ifname();
}
inline const ::std::string& SysInterfaceStruct::ifname() const {
  // @@protoc_insertion_point(field_get:SysInterfaceStruct.IFName)
  return *ifname_;
}
inline void SysInterfaceStruct::set_ifname(const ::std::string& value) {
  set_has_ifname();
  if (ifname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifname_ = new ::std::string;
  }
  ifname_->assign(value);
  // @@protoc_insertion_point(field_set:SysInterfaceStruct.IFName)
}
inline void SysInterfaceStruct::set_ifname(const char* value) {
  set_has_ifname();
  if (ifname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifname_ = new ::std::string;
  }
  ifname_->assign(value);
  // @@protoc_insertion_point(field_set_char:SysInterfaceStruct.IFName)
}
inline void SysInterfaceStruct::set_ifname(const char* value, size_t size) {
  set_has_ifname();
  if (ifname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifname_ = new ::std::string;
  }
  ifname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SysInterfaceStruct.IFName)
}
inline ::std::string* SysInterfaceStruct::mutable_ifname() {
  set_has_ifname();
  if (ifname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SysInterfaceStruct.IFName)
  return ifname_;
}
inline ::std::string* SysInterfaceStruct::release_ifname() {
  clear_has_ifname();
  if (ifname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ifname_;
    ifname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void SysInterfaceStruct::set_allocated_ifname(::std::string* ifname) {
  if (ifname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ifname_;
  }
  if (ifname) {
    set_has_ifname();
    ifname_ = ifname;
  } else {
    clear_has_ifname();
    ifname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SysInterfaceStruct.IFName)
}

// optional string IFPath = 4;
inline bool SysInterfaceStruct::has_ifpath() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SysInterfaceStruct::set_has_ifpath() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SysInterfaceStruct::clear_has_ifpath() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SysInterfaceStruct::clear_ifpath() {
  if (ifpath_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifpath_->clear();
  }
  clear_has_ifpath();
}
inline const ::std::string& SysInterfaceStruct::ifpath() const {
  // @@protoc_insertion_point(field_get:SysInterfaceStruct.IFPath)
  return *ifpath_;
}
inline void SysInterfaceStruct::set_ifpath(const ::std::string& value) {
  set_has_ifpath();
  if (ifpath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifpath_ = new ::std::string;
  }
  ifpath_->assign(value);
  // @@protoc_insertion_point(field_set:SysInterfaceStruct.IFPath)
}
inline void SysInterfaceStruct::set_ifpath(const char* value) {
  set_has_ifpath();
  if (ifpath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifpath_ = new ::std::string;
  }
  ifpath_->assign(value);
  // @@protoc_insertion_point(field_set_char:SysInterfaceStruct.IFPath)
}
inline void SysInterfaceStruct::set_ifpath(const char* value, size_t size) {
  set_has_ifpath();
  if (ifpath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifpath_ = new ::std::string;
  }
  ifpath_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SysInterfaceStruct.IFPath)
}
inline ::std::string* SysInterfaceStruct::mutable_ifpath() {
  set_has_ifpath();
  if (ifpath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ifpath_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SysInterfaceStruct.IFPath)
  return ifpath_;
}
inline ::std::string* SysInterfaceStruct::release_ifpath() {
  clear_has_ifpath();
  if (ifpath_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ifpath_;
    ifpath_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void SysInterfaceStruct::set_allocated_ifpath(::std::string* ifpath) {
  if (ifpath_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ifpath_;
  }
  if (ifpath) {
    set_has_ifpath();
    ifpath_ = ifpath;
  } else {
    clear_has_ifpath();
    ifpath_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SysInterfaceStruct.IFPath)
}

// optional int32 IsEnable = 5;
inline bool SysInterfaceStruct::has_isenable() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SysInterfaceStruct::set_has_isenable() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SysInterfaceStruct::clear_has_isenable() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SysInterfaceStruct::clear_isenable() {
  isenable_ = 0;
  clear_has_isenable();
}
inline ::google::protobuf::int32 SysInterfaceStruct::isenable() const {
  // @@protoc_insertion_point(field_get:SysInterfaceStruct.IsEnable)
  return isenable_;
}
inline void SysInterfaceStruct::set_isenable(::google::protobuf::int32 value) {
  set_has_isenable();
  isenable_ = value;
  // @@protoc_insertion_point(field_set:SysInterfaceStruct.IsEnable)
}

// optional string DescComment = 6;
inline bool SysInterfaceStruct::has_desccomment() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SysInterfaceStruct::set_has_desccomment() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SysInterfaceStruct::clear_has_desccomment() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SysInterfaceStruct::clear_desccomment() {
  if (desccomment_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desccomment_->clear();
  }
  clear_has_desccomment();
}
inline const ::std::string& SysInterfaceStruct::desccomment() const {
  // @@protoc_insertion_point(field_get:SysInterfaceStruct.DescComment)
  return *desccomment_;
}
inline void SysInterfaceStruct::set_desccomment(const ::std::string& value) {
  set_has_desccomment();
  if (desccomment_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desccomment_ = new ::std::string;
  }
  desccomment_->assign(value);
  // @@protoc_insertion_point(field_set:SysInterfaceStruct.DescComment)
}
inline void SysInterfaceStruct::set_desccomment(const char* value) {
  set_has_desccomment();
  if (desccomment_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desccomment_ = new ::std::string;
  }
  desccomment_->assign(value);
  // @@protoc_insertion_point(field_set_char:SysInterfaceStruct.DescComment)
}
inline void SysInterfaceStruct::set_desccomment(const char* value, size_t size) {
  set_has_desccomment();
  if (desccomment_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desccomment_ = new ::std::string;
  }
  desccomment_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:SysInterfaceStruct.DescComment)
}
inline ::std::string* SysInterfaceStruct::mutable_desccomment() {
  set_has_desccomment();
  if (desccomment_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desccomment_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:SysInterfaceStruct.DescComment)
  return desccomment_;
}
inline ::std::string* SysInterfaceStruct::release_desccomment() {
  clear_has_desccomment();
  if (desccomment_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = desccomment_;
    desccomment_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void SysInterfaceStruct::set_allocated_desccomment(::std::string* desccomment) {
  if (desccomment_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete desccomment_;
  }
  if (desccomment) {
    set_has_desccomment();
    desccomment_ = desccomment;
  } else {
    clear_has_desccomment();
    desccomment_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:SysInterfaceStruct.DescComment)
}

// -------------------------------------------------------------------

// InterfaceSelectReq

// optional int32 DSSVRID = 2;
inline bool InterfaceSelectReq::has_dssvrid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InterfaceSelectReq::set_has_dssvrid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InterfaceSelectReq::clear_has_dssvrid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InterfaceSelectReq::clear_dssvrid() {
  dssvrid_ = 0;
  clear_has_dssvrid();
}
inline ::google::protobuf::int32 InterfaceSelectReq::dssvrid() const {
  // @@protoc_insertion_point(field_get:InterfaceSelectReq.DSSVRID)
  return dssvrid_;
}
inline void InterfaceSelectReq::set_dssvrid(::google::protobuf::int32 value) {
  set_has_dssvrid();
  dssvrid_ = value;
  // @@protoc_insertion_point(field_set:InterfaceSelectReq.DSSVRID)
}

// -------------------------------------------------------------------

// InterfaceSelectAck

// repeated .SysInterfaceStruct CfgItems = 2;
inline int InterfaceSelectAck::cfgitems_size() const {
  return cfgitems_.size();
}
inline void InterfaceSelectAck::clear_cfgitems() {
  cfgitems_.Clear();
}
inline const ::SysInterfaceStruct& InterfaceSelectAck::cfgitems(int index) const {
  // @@protoc_insertion_point(field_get:InterfaceSelectAck.CfgItems)
  return cfgitems_.Get(index);
}
inline ::SysInterfaceStruct* InterfaceSelectAck::mutable_cfgitems(int index) {
  // @@protoc_insertion_point(field_mutable:InterfaceSelectAck.CfgItems)
  return cfgitems_.Mutable(index);
}
inline ::SysInterfaceStruct* InterfaceSelectAck::add_cfgitems() {
  // @@protoc_insertion_point(field_add:InterfaceSelectAck.CfgItems)
  return cfgitems_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
InterfaceSelectAck::cfgitems() const {
  // @@protoc_insertion_point(field_list:InterfaceSelectAck.CfgItems)
  return cfgitems_;
}
inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
InterfaceSelectAck::mutable_cfgitems() {
  // @@protoc_insertion_point(field_mutable_list:InterfaceSelectAck.CfgItems)
  return &cfgitems_;
}

// -------------------------------------------------------------------

// InterfaceInsertReq

// repeated .SysInterfaceStruct CfgItems = 2;
inline int InterfaceInsertReq::cfgitems_size() const {
  return cfgitems_.size();
}
inline void InterfaceInsertReq::clear_cfgitems() {
  cfgitems_.Clear();
}
inline const ::SysInterfaceStruct& InterfaceInsertReq::cfgitems(int index) const {
  // @@protoc_insertion_point(field_get:InterfaceInsertReq.CfgItems)
  return cfgitems_.Get(index);
}
inline ::SysInterfaceStruct* InterfaceInsertReq::mutable_cfgitems(int index) {
  // @@protoc_insertion_point(field_mutable:InterfaceInsertReq.CfgItems)
  return cfgitems_.Mutable(index);
}
inline ::SysInterfaceStruct* InterfaceInsertReq::add_cfgitems() {
  // @@protoc_insertion_point(field_add:InterfaceInsertReq.CfgItems)
  return cfgitems_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
InterfaceInsertReq::cfgitems() const {
  // @@protoc_insertion_point(field_list:InterfaceInsertReq.CfgItems)
  return cfgitems_;
}
inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
InterfaceInsertReq::mutable_cfgitems() {
  // @@protoc_insertion_point(field_mutable_list:InterfaceInsertReq.CfgItems)
  return &cfgitems_;
}

// -------------------------------------------------------------------

// InterfaceInsertAck

// optional int32 Ret = 2;
inline bool InterfaceInsertAck::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InterfaceInsertAck::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InterfaceInsertAck::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InterfaceInsertAck::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 InterfaceInsertAck::ret() const {
  // @@protoc_insertion_point(field_get:InterfaceInsertAck.Ret)
  return ret_;
}
inline void InterfaceInsertAck::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:InterfaceInsertAck.Ret)
}

// -------------------------------------------------------------------

// InterfaceUpdateReq

// repeated .SysInterfaceStruct CfgItems = 2;
inline int InterfaceUpdateReq::cfgitems_size() const {
  return cfgitems_.size();
}
inline void InterfaceUpdateReq::clear_cfgitems() {
  cfgitems_.Clear();
}
inline const ::SysInterfaceStruct& InterfaceUpdateReq::cfgitems(int index) const {
  // @@protoc_insertion_point(field_get:InterfaceUpdateReq.CfgItems)
  return cfgitems_.Get(index);
}
inline ::SysInterfaceStruct* InterfaceUpdateReq::mutable_cfgitems(int index) {
  // @@protoc_insertion_point(field_mutable:InterfaceUpdateReq.CfgItems)
  return cfgitems_.Mutable(index);
}
inline ::SysInterfaceStruct* InterfaceUpdateReq::add_cfgitems() {
  // @@protoc_insertion_point(field_add:InterfaceUpdateReq.CfgItems)
  return cfgitems_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
InterfaceUpdateReq::cfgitems() const {
  // @@protoc_insertion_point(field_list:InterfaceUpdateReq.CfgItems)
  return cfgitems_;
}
inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
InterfaceUpdateReq::mutable_cfgitems() {
  // @@protoc_insertion_point(field_mutable_list:InterfaceUpdateReq.CfgItems)
  return &cfgitems_;
}

// -------------------------------------------------------------------

// InterfaceUpdateAck

// optional int32 Ret = 2;
inline bool InterfaceUpdateAck::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InterfaceUpdateAck::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InterfaceUpdateAck::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InterfaceUpdateAck::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 InterfaceUpdateAck::ret() const {
  // @@protoc_insertion_point(field_get:InterfaceUpdateAck.Ret)
  return ret_;
}
inline void InterfaceUpdateAck::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:InterfaceUpdateAck.Ret)
}

// -------------------------------------------------------------------

// InterfaceDeleteReq

// repeated .SysInterfaceStruct CfgItems = 2;
inline int InterfaceDeleteReq::cfgitems_size() const {
  return cfgitems_.size();
}
inline void InterfaceDeleteReq::clear_cfgitems() {
  cfgitems_.Clear();
}
inline const ::SysInterfaceStruct& InterfaceDeleteReq::cfgitems(int index) const {
  // @@protoc_insertion_point(field_get:InterfaceDeleteReq.CfgItems)
  return cfgitems_.Get(index);
}
inline ::SysInterfaceStruct* InterfaceDeleteReq::mutable_cfgitems(int index) {
  // @@protoc_insertion_point(field_mutable:InterfaceDeleteReq.CfgItems)
  return cfgitems_.Mutable(index);
}
inline ::SysInterfaceStruct* InterfaceDeleteReq::add_cfgitems() {
  // @@protoc_insertion_point(field_add:InterfaceDeleteReq.CfgItems)
  return cfgitems_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >&
InterfaceDeleteReq::cfgitems() const {
  // @@protoc_insertion_point(field_list:InterfaceDeleteReq.CfgItems)
  return cfgitems_;
}
inline ::google::protobuf::RepeatedPtrField< ::SysInterfaceStruct >*
InterfaceDeleteReq::mutable_cfgitems() {
  // @@protoc_insertion_point(field_mutable_list:InterfaceDeleteReq.CfgItems)
  return &cfgitems_;
}

// -------------------------------------------------------------------

// InterfaceDeleteAck

// optional int32 Ret = 2;
inline bool InterfaceDeleteAck::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InterfaceDeleteAck::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InterfaceDeleteAck::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InterfaceDeleteAck::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 InterfaceDeleteAck::ret() const {
  // @@protoc_insertion_point(field_get:InterfaceDeleteAck.Ret)
  return ret_;
}
inline void InterfaceDeleteAck::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:InterfaceDeleteAck.Ret)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DSMsg_2eproto__INCLUDED
